#ifndef GEMINI_UTILS_H
#define GEMINI_UTILS_H

enum Status
{
    // 1
    INPUT = 10,
    SENSITIVE_INPUT = 11,
    // 2
    SUCCESS = 20,
    // 3
    REDIRECT_TEMPORARY = 30,
    REDIRECT_PERMANENT = 31,
    // 4
    TEMPORARY_FAILURE = 40,
    SERVER_UNAVAILABLE = 41,
    CGI_ERROR = 42,
    PROXY_ERROR = 43,
    SLOW_DOWN = 44,
    // 5
    PERMANENT_FAILURE = 50,
    NOT_FOUND = 51,
    GONE = 52,
    PROXY_REQUEST_REFUSED = 53,
    BAD_REQUEST = 59,
    // 6
    CLIENT_CERTIFICATE_REQUIRED = 60,
    CERTIFICATE_NOT_AUTHORISED = 61,
    CERTIFICATE_NOT_VALID = 62,
};

#endif // !GEMINI_UTILS_H